I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-a2-scene2-mo.rpy", line 5, in script
    show mo45 at tispot
  File "game/script-a2-scene2-mo.rpy", line 5, in <module>
    show mo45 at tispot
NameError: name 'tispot' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-a2-scene2-mo.rpy", line 5, in script
    show mo45 at tispot
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1156, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script-a2-scene2-mo.rpy", line 5, in <module>
    show mo45 at tispot
NameError: name 'tispot' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
LOVExCOMPUTER 1.0
Sat Apr  2 21:50:09 2022
